name: core_fe_dart
description: Shared utilities layer to all layers across the application, it's framework independent
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  mockito: ^4.1.1
  logger: ^0.9.1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
