name: core_fe_dart
description: Shared utilities layer to all layers across the application, it's framework independent
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  tuple: ^1.0.3
  equatable: ^1.2.2

dev_dependencies:
  pedantic: ^1.9.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
